services:
  # ===================== service oquiz API ================
  oquiz-db:
    image: postgres:17 # Image permettant de créer le conteneur
    restart: unless-stopped # Redémarre automatiquement mon service en cas de crash (sauf si je l'ai éteint manuellement)
    networks:
      - oquiz-network
    volumes:
      - oquiz-db-volume:/var/lib/postgresql/data # je monte mon volume oquiz-data dans mon conteneur, là où Postgres écrit par défaut ses données lorsqu'il manipule les tables
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: # Si on a besoin de pouvoir contacter la BDD depuis l'extérieur, on peut rajouter ce binding de port, sinon pas besoin
      # PORT_LOCAL:PORT_CONTENEUR
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  oquiz-api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      PORT: ${API_LOCAL_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@oquiz-db:5432/${POSTGRES_DB}
      NODE_ENV: development
      LOGS_PATH: ${API_LOGS_PATH}
    ports:
      - ${API_LOCAL_PORT}:${API_LOCAL_PORT}
    volumes:
      # On crée un bind volume pour le code source, qui nous permettra de développer au sein du conteneur -> on redirige l'utilisation du dossier /app depuis le conteneur vers le dossier local /api => permet le hot reload en dev
      - ./api:/app
      - /app/node_modules # Exclure les node_modules local, et utiliser uniquement ceux du conteneur
    networks:
      - oquiz-network
    depends_on:
      oquiz-db:
        condition: service_healthy
    command: npm run docker:dev

  oquiz-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:${API_LOCAL_PORT}
    ports:
      - ${CLIENT_LOCAL_PORT}:5173
    volumes:
      # Monter le code source pour le hot reload
      - ./client:/app
      # Exclure node_modules pour utiliser ceux du conteneur
      - /app/node_modules
    networks:
      - oquiz-network

  # ===================== service oquiz LOGS ================

  logs-api:
    build:
      context: ./log-service
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      PORT: ${LOGS_API_LOCAL_PORT}
      NODE_ENV: development
      MONGODB_URI: mongodb://logs-db:27017/logs_db
      DATABASE_URL: mongodb://logs-db:27017/logs_db
    ports:
      - ${LOGS_API_LOCAL_PORT}:${LOGS_API_LOCAL_PORT}
    volumes:
      - ./log-service:/app
      - /app/node_modules
    networks:
      - oquiz-network
    command: npm run dev
    depends_on:
      - logs-db


  logs-db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - ${LOGS_DB_LOCAL_PORT}:27017
    networks:
      - oquiz-network
    command: mongod --quiet --logpath /dev/null # commmande pour lancer mongo en mode "quiet" pas trop de logs
    volumes:
     - logs-db-volume:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 10
    
networks:
  oquiz-network:

volumes:
  oquiz-db-volume:
  logs-db-volume:

  
