services:
  oquiz-db:
    image: postgres:17 # Image permettant de créer le conteneur
    restart: unless-stopped # Redémarre automatiquement mon service en cas de crash (sauf si je l'ai éteint manuellement)
    networks:
      - oquiz-network
    volumes:
      - oquiz-db-volume:/var/lib/postgresql/data # je monte mon volume oquiz-data dans mon conteneur, là où Postgres écrit par défaut ses données lorsqu'il manipule les tables
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: # Si on a besoin de pouvoir contacter la BDD depuis l'extérieur, on peut rajouter ce binding de port, sinon pas besoin
      # PORT_LOCAL:PORT_CONTENEUR
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  oquiz-api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      PORT: ${API_LOCAL_PORT}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    ports:
      - ${API_LOCAL_PORT}:${API_LOCAL_PORT}
    volumes:
      # On crée un bind volume pour le code source, qui nous permettra de développer au sein du conteneur -> on redirige l'utilisation du dossier /app depuis le conteneur vers le dossier local /api => permet le hot reload en dev
      - ./api:/app
      - /app/node_modules # Exclure les node_modules local, et utiliser uniquement ceux du conteneur
    networks:
      - oquiz-network
    depends_on:
      oquiz-db:
        condition: service_healthy

  oquiz-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - ${CLIENT_LOCAL_PORT}:5173
    volumes:
      # Monter le code source pour le hot reload
      - ./client:/app
      # Exclure node_modules pour utiliser ceux du conteneur
      - /app/node_modules
    networks:
      - oquiz-network

networks:
  oquiz-network:

volumes:
  oquiz-db-volume:
